### ISSUE TITLE
PeerID Based Address Filtering

### ISSUE THREAD

**Issue by bonedaddy** [libp2p/go-maddr-filter#15]
Is there any desire to have PeerID  based filtering within `go-maddr-filter`? I'm currently working peerID based filtering in a fork of this repository, however if there is desire to have this kind of functionality, it might be worth spec'ing it out formally and I'd be happy to implement it since I'm doing so anyways for my own needs.

**Comment by olizilla** [comment]
I want peer id based filtering.

**Comment by raulk** [comment]
Closing down as a duplicate. Please track the Connection Gating epic https://github.com/libp2p/go-libp2p/issues/872.
