### ISSUE TITLE
Interface for filtering addresses

### ISSUE THREAD

**Issue by meyer9** [libp2p/go-maddr-filter#9]
go-maddr-filter should be abstracted to an interface that provides a multiaddr filter like this:

```go
interface AddrFilter {
    AddrBlocked(a ma.Multiaddr) bool
}
```

This would allow users to write custom filtering code (ban system) and use it in place of go-maddr-filter.

**Comment by ghost** [comment]
Relevant multiaddr issue: multiformats/multiaddr#88

**Comment by raulk** [comment]
This work is being done as part of the **Connection Gating** feature of libp2p. Track https://github.com/libp2p/go-libp2p/issues/872.
